FROM centos

MAINTAINER vinodd@samanvayfoundation.org

RUN yum install -y \
       java-1.8.0-openjdk \
       java-1.8.0-openjdk-devel

ENV JAVA_HOME /etc/alternatives/jre

RUN yum -y install initscripts && yum clean all && yum -y install unzip && yum -y install git && yum -y install nodejs
RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash
RUN npm install --global yarn

VOLUME /tmp

EXPOSE 8021
EXPOSE 3000

RUN mkdir /etc/openchs

COPY resources/avni.conf /tmp/avni.conf

COPY resources/avni.sh /tmp/avni.sh

COPY resources/avni-server.rpm /tmp/avni-server.rpm

COPY resources/avni-webapp.zip /tmp/avni-webapp.zip

ENTRYPOINT ["/tmp/avni.sh"]

CMD tail -f /dev/null
