FROM ubuntu:20.04

LABEL maintainer "vinodd@samanvayfoundation.org"

WORKDIR /

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y openjdk-8-jdk vim git unzip libglu1 libpulse-dev libasound2 libc6  libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxi6  libxtst6 libnss3 wget && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends qemu-kvm virtinst bridge-utils cpu-checker xfce4 xfce4-goodies xfonts-base dbus-x11 tightvncserver expect gnome-core xfce4 firefox

ARG GRADLE_VERSION=5.4.1
ARG ANDROID_API_LEVEL=27
ARG ANDROID_BUILD_TOOLS_LEVEL=28.0.3
ARG EMULATOR_NAME='test'

RUN wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -P /tmp \
&& unzip -d /opt/gradle /tmp/gradle-${GRADLE_VERSION}-bin.zip \
&& mkdir /opt/gradlew \
&& /opt/gradle/gradle-${GRADLE_VERSION}/bin/gradle wrapper --gradle-version ${GRADLE_VERSION} --distribution-type all -p /opt/gradlew  \
&& /opt/gradle/gradle-${GRADLE_VERSION}/bin/gradle wrapper -p /opt/gradlew

RUN wget 'https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip' -P /tmp \
&& unzip -d /opt/android /tmp/sdk-tools-linux-4333796.zip \
&& yes Y | /opt/android/tools/bin/sdkmanager --install "platform-tools" "system-images;android-${ANDROID_API_LEVEL};google_apis;x86" "platforms;android-${ANDROID_API_LEVEL}" "build-tools;${ANDROID_BUILD_TOOLS_LEVEL}" "emulator" \
&& yes Y | /opt/android/tools/bin/sdkmanager --licenses \
&& echo "no" | /opt/android/tools/bin/avdmanager --verbose create avd --force --name "test" --device "pixel" --package "system-images;android-${ANDROID_API_LEVEL};google_apis;x86" --tag "google_apis" --abi "x86"

ENV GRADLE_HOME=/opt/gradle/gradle-$GRADLE_VERSION \
ANDROID_HOME=/opt/android
ENV PATH "$PATH:$GRADLE_HOME/bin:/opt/gradlew:$ANDROID_HOME/emulator:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools"
ENV LD_LIBRARY_PATH "$ANDROID_HOME/emulator/lib64:$ANDROID_HOME/emulator/lib64/qt/lib"

COPY /resources/emulator.sh /tmp/emulator.sh
COPY /resources/xstatup /root/.vnc/xstatup

RUN chmod +x /tmp/emulator.sh

RUN printf "password\npassword\n\n" | vncpasswd

ENV USER root
ENV DISPLAY :1.0
EXPOSE 5037
EXPOSE 5901

ADD https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-d774-2020-08-20-14-47-11.apk /home/avni.apk

RUN echo "hw.keyboard=yes" >> /root/.android/avd/test.avd/config.ini

ENTRYPOINT ["/tmp/emulator.sh"]
