version: '3.1'
services:
  server:
    container_name: avni-server
    image: vind3v/avni-server:3.7
    ports:
      - "8021:8021"
      - "3000:3000"
    depends_on:
      - db
    networks:
      - avninet

  db:
    container_name: avni-db
    image: vind3v/avni-db:12.3
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=openchs
      - POSTGRES_DB=openchs
    networks:
      - avninet
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  avninet:
    driver: bridge

volumes:
  pgdata:

